Title: Whatis Credentials.py, Why Does Pycharm Show Full Module Name for Tests
Date: Oct 3 2021
Modified: Oct 3 2021 8:15 MST
Category: tech
Tags: tests doctests python

I started writing a credentials helper, mostly as an excuse to get familiar with a templating library in Python. It's a little cli tool
to generate a yaml file, nothing specially tough or tricky but some code to write.

I wanted to keep dependencies to a bare minimum, make things easy to package, so I decided to write the whole thing in one file. I wanted
to package the tests into that file too, the whole kit and kaboodle, so I decided to use doctests as a way to force myself to keep the tests
very local to the code.

That has consequences for the granularity of the tests, I guess, but who cares about that.

On to the problem:

# Why Does the Pycharm IDE Show a Different Name For Modules than my CLI Tests?

When I have a failing test in Pycharm, I get a stack trace that has this at the end (there are unclosed string tags, so the highlighting is
a little weird):

```python
File "/Users/gwyn/Developer/jinkies/credentials_helper/credentials.py", line 55, in get_credential_template_path_from_argv
raise CredentialNameNotFound(f"""--credential specified, but no credential type given. Valid credentials are
credentials.CredentialNameNotFound: --credential specified, but no credential type given. Valid credentials are
party_down you supplied <None>
```

When I have the same failing test run from my CLI, I get this:
```python
File "/Users/gwyn/Developer/jinkies/credentials_helper/credentials.py", line 55, in get_credential_template_path_from_argv
raise CredentialNameNotFound(f"""--credential specified, but no credential type given. Valid credentials are
CredentialNameNotFound: --credential specified, but no credential type given. Valid credentials are
party_down you supplied <None>
```

The difference I want to drawn your eyes to is on line 3 of each: `credentials.CredentialNameNotFound` vs `CredentialNameNotFound`. This difference makes it impossible to pass my tests in both the CLI and Pycharm simultaneously.

I figured out the cause of the difference: Pycharm's debugger is an external process peering into the application. You can see this in pycharm's full stack traces on this line:

```python
      File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/docrunner.py", line 138, in __run
```

If you go read the docrunner, it does some formatting towards TeamCity style test results, but nothing magical otherwise.

How I was invoking doctest was with this cute little method inside of Credentials.py:
```python
    # Sneaky sneak flag to run the doctests ðŸ¤«
    if "--run-tests" in private_argv:
        import doctest
        doctest.testmod()
        sys.exit(0)
```

This runs from within the same context as the Credentials module, so the module name doesn't need to be resolved.

To fix it, I wrote a helper shell script to execute the tests with an explicit invocation. I don't need no --run-tests flag:

```python
#!/usr/bin/env bash -el

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${THIS_SCRIPT_DIR}

python3 -m doctest credentials.py
```

But if you did need a --run-tests flag, you could probably just recreate the above as a string and use subprocess.call to execute it.
